from enum import StrEnum

class ClaimType(StrEnum):
    FACTUAL_CLAIM="FACTUAL_CLAIM"; PROJECTION="PROJECTION"; PROMISE="PROMISE"; OPINION="OPINION"; VALUE_JUDGMENT="VALUE_JUDGMENT"; RHETORICAL="RHETORICAL"; ANECDOTAL="ANECDOTAL"; ATTRIBUTION="ATTRIBUTION"; QUOTE="QUOTE"; NOT_CHECKABLE="NOT_CHECKABLE"
class ClaimStatus(StrEnum):
    DETECTED="DETECTED"; RESEARCHING="RESEARCHING"; AI_REVIEWED="AI_REVIEWED"; EDITORIAL_REVIEW="EDITORIAL_REVIEW"; PUBLISHED="PUBLISHED"; CORRECTED="CORRECTED"; RETRACTED="RETRACTED"
class Verdict(StrEnum):
    SUPPORTED="SUPPORTED"; MOSTLY_SUPPORTED="MOSTLY_SUPPORTED"; NEEDS_CONTEXT="NEEDS_CONTEXT"; UNSUPPORTED="UNSUPPORTED"; FALSE="FALSE"; INCONCLUSIVE="INCONCLUSIVE"; NOT_CHECKABLE="NOT_CHECKABLE"
class EvidenceStance(StrEnum):
    SUPPORT="SUPPORT"; REFUTE="REFUTE"; CONTEXT="CONTEXT"; NEUTRAL="NEUTRAL"
class SourceType(StrEnum):
    PRIMARY_OFFICIAL="PRIMARY_OFFICIAL"; PRIMARY_RESEARCH="PRIMARY_RESEARCH"; PRIMARY_LEGAL="PRIMARY_LEGAL"; SECONDARY_EXPERT="SECONDARY_EXPERT"; SECONDARY_JOURNALISTIC="SECONDARY_JOURNALISTIC"; STAKEHOLDER="STAKEHOLDER"; SOCIAL_MEDIA="SOCIAL_MEDIA"; UNKNOWN="UNKNOWN"
